version: 2
jobs:
  apt-get:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Installing tools and libraries
          command: 'apt-get update && apt-get install -y sudo gcc g++ cmake libzip-dev libboost-dev libboost-filesystem-dev libboost-test-dev && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Configuring
          command: 'cmake -H. -Bbuild -DFMI4CPP_BUILD_TESTS=ON -DFMI4CPP_BUILD_EXAMPLES=ON'
      - run:
          name: Building
          command: 'cmake --build build'
      - run:
          name: Unit tests
          command: 'cd build/tests && ctest'
  conan:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
            name: Install tools
            command: 'apt-get update && apt-get install -y sudo python3-setuptools python3-wheel python3-pip && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Install stuff
          command: 'sudo pip3 install cmake conan '

      - restore_cache:
          keys:
            - conan-cache-v2--{{ checksum "conanfile.txt" }}
            - conan-cache-v2
      - run:
          name: Conan install
          command: 'conan install . -s build_type=Debug -s compiler.libcxx=libstdc++11 --install-folder=build'

      - save_cache:
          paths:
            - ~/.conan
          key: conan-cache-v2--{{ checksum "conanfile.txt" }}

      - run:
          name: Configuring
          command: 'cmake -H. -Bbuild -DFMI4CPP_USING_CONAN=ON -DFMI4CPP_BUILD_TESTS=ON -DFMI4CPP_BUILD_EXAMPLES=ON'
      - run:
          name: Building
          command: 'cmake --build build'
      - run:
          name: Unit tests
          command: 'cd build/tests && ctest'


workflows:
  version: 2
  build:
    jobs:
      - apt-get
      - conan
